### ISSUE TITLE
Random crash in csvpn.exe in KERNELBASE.dll

### ISSUE THREAD

**Issue by bricky149** [cryptostorm/cstorm_widget#1]
No steps to reproduce as it can happen out of the blue while running the client. CS Twitter operator (assuming p_j) has passed it on to df for review.

Since Windows sucks with program debugging I have no log to upload.

**Comment by pjstorm** [comment]
Has it only happened with a particular widget build, or is it generalised across builds?

**Comment by bricky149** [comment]
First noticed in 2.22 but it could be generalised.

Wow, I neglected this. Apologies.

**Comment by df-cryptostorm** [comment]
Yea, thanks to the nature of these types of crashes, it's very difficult for me to reproduce.
Even if I loaded up the same Windows OS you're using, and performed the same network task you were doing, the bug will most likely not show up.

The only real way to accurately debug these types of errors would be for you to install ActivePerl and the modules client.pl uses, then to put client.pl in C:\Program Files (x86)\Cryptostorm Client\bin\ and execute it with perl. 

Doing it that way, you could change the first 3 lines of client.pl from:
#!/usr/bin/perl #-d:Trace
#open(STDERR, ">&STDOUT") or warn "failed to dup STDOUT:$!";
#$Devel::Trace::TRACE = 1;

to:
#!/usr/bin/perl -d:Trace
open(STDERR, ">&STDOUT") or warn "failed to dup STDOUT:$!";
$Devel::Trace::TRACE = 1;

To be given a bunch of debug logging output.

But asking people to do all of the above is a bit much. I'm still looking into a better way to catch crashes like this. Can't really use the Perl ways for catching crashes because often times it's not Perl that's crashing, it's something used by the Cava Packager (which is used to get client.exe out of client.pl).

So I'm still looking :-)
