### ISSUE TITLE
[Request] Redistributable *.ovpn files for those not using widget

### ISSUE THREAD

**Issue by bricky149** [cryptostorm/cstorm_widget#3]
I would like to be able to use the *.ovpn files CStorm uses outside of the widget/client.

**Comment by df-cryptostorm** [comment]
In the later versions, I decided to stop using external config files to make it easier to deal with the different protocols (and cryptofree). Otherwise, I would have either had to dynamically generate the config on connect, or create ovpn config files for each instance.

But you can still see the ovpn config syntax used in the source code, in line 839 to 872:
(I'm including # style comments here not in the source code to make it easier to understand)

#$port_var is the port you'll use to connect, $proto_var is either TCP or UDP
#for cryptofree:
   if ($proto_var eq "UDP") {
    $vpn_args = "--client --dev tun --proto udp --remote windows-cryptofree1-a.cstorm.pw $port_var --remote windows-cryptofree1-a.cryptostorm.net $port_var --remote windows-cryptofree1-a.cryptostorm.org $port_var --resolv-retry infinite --nobind --comp-lzo --down-pre --reneg-sec 0 --explicit-exit-notify 3 --hand-window 17 --fragment 1400 --verb 4 --mute 3 --auth-user-pass client.dat --ca ca2.crt --ns-cert-type server --auth SHA512 --cipher AES-256-CBC --tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA --tls-client --key-method 2";
   }
   if ($proto_var eq "TCP") {
    $vpn_args = "--client --dev tun --proto tcp --remote windows-cryptofree1-a.cstorm.pw $port_var --remote windows-cryptofree1-a.cryptostorm.net $port_var --remote windows-cryptofree1-a.cryptostorm.org $port_var --resolv-retry infinite --nobind --comp-lzo --down-pre --reneg-sec 0 --hand-window 17 --verb 4 --mute 3 --auth-user-pass client.dat --ca ca2.crt --ns-cert-type server --auth SHA512 --cipher AES-256-CBC --tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA --tls-client --key-method 2";
   }
  }
#for other servers (the paid ones):
   if ($proto_var eq "UDP") {
    if ($server eq "Global random") {
     $vpn_args = "--client --dev tun --proto udp --remote windows-balancer.cstorm.pw $port_var --remote windows-balancer.cryptostorm.net $port_var --remote windows-balancer.cryptostorm.org $port_var --resolv-retry infinite --nobind --comp-lzo --down-pre --reneg-sec 0 --explicit-exit-notify 3 --hand-window 17 --fragment 1400 --verb 4 --mute 3 --auth-user-pass client.dat --ca ca2.crt --ns-cert-type server --auth SHA512 --cipher AES-256-CBC --tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA --tls-client --key-method 2";
	}
	else {
	# here $tmpline is the last field in https://cryptostorm.nu/nodelist.txt (the hostname at the end, using : as a delimiter).
	# for example, in the first line of nodelist.txt:
	# Paris - France:France:windows:windows-paris.cstorm.pw
	# in that case, $tmpline would be "windows-paris"
	 $vpn_args = "--client --dev tun --proto udp --remote $tmpline.cstorm.pw $port_var --remote $tmpline.cryptostorm.net $port_var --remote $tmpline.cryptostorm.org $port_var --resolv-retry infinite --nobind --comp-lzo --down-pre --reneg-sec 0 --explicit-exit-notify 3 --hand-window 17 --fragment 1400 --verb 4 --mute 3 --auth-user-pass client.dat --ca ca2.crt --ns-cert-type server --auth SHA512 --cipher AES-256-CBC --tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA --tls-client --key-method 2";
	}
   }
   if ($proto_var eq "TCP") {
    if ($server eq "Global random") {
     $vpn_args = "--client --dev tun --proto tcp --remote windows-balancer.cstorm.pw $port_var --remote windows-balancer.cryptostorm.net $port_var --remote windows-balancer.cryptostorm.org $port_var --resolv-retry infinite --nobind --comp-lzo --down-pre --reneg-sec 0 --hand-window 17 --verb 4 --mute 3 --auth-user-pass client.dat --ca ca2.crt --ns-cert-type server --auth SHA512 --cipher AES-256-CBC --tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA --tls-client --key-method 2";
	}
	else {
	# same applies 
	 $vpn_args = "--client --dev tun --proto tcp --remote $tmpline.cstorm.pw $port_var --remote $tmpline.cryptostorm.net $port_var --remote $tmpline.cryptostorm.org $port_var --resolv-retry infinite --nobind --comp-lzo --down-pre --reneg-sec 0 --hand-window 17 --verb 4 --mute 3 --auth-user-pass client.dat --ca ca2.crt --ns-cert-type server --auth SHA512 --cipher AES-256-CBC --tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA --tls-client --key-method 2";
    }
   }
  }

So to create a .ovpn config file out of the values in $vpn_args, you would replace the $variables with whatever content they should be, then put all of those config directives in a .ovpn file (I'm pretty sure you need to get rid of the two dashes at the beginning of each config directive).

Eventually, I'll just copy/paste most of that code into a server-side CGI script so people can generate their own .ovpn files just by visiting https://cryptostorm.is/confgen (or wherever it ends up being)

**Comment by df-cryptostorm** [comment]
EDIT: We've got these at https://github.com/cryptostorm/cryptostorm_client_configuration_files now in the 'windows' folder.
