### ISSUE TITLE
Desktop client for Linux-based operating systems with easy obfuscation options

### ISSUE THREAD

**Issue by baimafeima** [cryptostorm/cstorm_widget#5]
Do you have any plans to develop your own desktop client for Linux-based operating systems? It would be great to have one client application which is lean (no binaries) and comes with dependencies which can be locally met on my operating system of choice. It would also be great if such client would have a simple boxes to select between various obfuscation techniques such as `stunnel`, `openconnect` (run openconnect on top of OpenVPN to prevent DPI inspection), `SSH`, `obfs4`, `XOR`, `multihop`, etc.

**Comment by df-cryptostorm** [comment]
You can't have a client application without binaries. An "application" is just a program, which is a binary file. The problem with using local dependencies is that a lot of Linux distros have outdated libraries, especially OpenSSL, which OpenVPN is dependent on. So any Linux client we do would need to include the latest libraries, probably statically linked to shared objects that would be bundled with the client, to prevent the client from using potentially outdated libraries on the system. A Linux client is still on the todo list, but there are a lot of things higher in that list that need to be completed first. We don't support OpenConnect or XOR since those methods don't do anything for DPI, but we do support HTTPS tunneling via stunnel, SSH tunneling, and obfs4. Multihopping can be done with any VPN that runs OpenVPN or WireGuard. Writing a GUI for something like that is complicated, but for now we do have [https://cryptostorm.is/multihop](https://cryptostorm.is/multihop) explaining how to do it in OpenVPN, and [https://cryptostorm.is/blog/multihopping-wireguard](https://cryptostorm.is/blog/multihopping-wireguard) explains how to do it in WireGuard.

And yes, I realize I'm answering this 7 years later, I just didn't like that it was closed in 2021 with no explanation.
